# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('facility_type', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Inspections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(max_length=50)),
                ('inspection_date', models.DateField()),
                ('critical_points', models.IntegerField()),
                ('total_points', models.IntegerField()),
                ('inspection_details', models.TextField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.Facility')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together=set([('name', 'facility_type', 'address', 'city')]),
        ),
    ]
