# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_auto_20160225_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterModelOptions(
            name='inspections',
            options={'ordering': ['-inspection_date'], 'verbose_name_plural': 'Inspections'},
        ),
    ]
