# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_auto_20160225_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspections',
            old_name='facility',
            new_name='facility_guid',
        ),
        migrations.AddField(
            model_name='facility',
            name='guid',
            field=models.UUIDField(default='placeholder', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='facility',
            name='id',
        ),
    ]
