# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='name',
            new_name='facility_name',
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together=set([('facility_name', 'facility_type', 'address', 'city')]),
        ),
    ]
