# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_auto_20160225_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='city',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
