# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    FacilityModel = apps.get_model('inspections', 'Facility')
    for row in FacilityModel.objects.all():
        row.guid = uuid.uuid4()
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_auto_20160227_0253'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
