# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0007_auto_20160227_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='guid',

    field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
