# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_auto_20160227_0904'),
    ]

    operations = [
         migrations.RemoveField(
          model_name='inspections',
            name='facility_guid',

        ),
        migrations.AlterField(
            model_name='facility',
            name='guid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),

        migrations.AlterUniqueTogether(
            name='facility',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='facility',
            name='id',
        ),
    ]
