# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0010_inspections_facility_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspections',
            name='facility_guid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspections.Facility'),
        ),
    ]
