# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 07:46
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callid', models.IntegerField()),
                ('nature', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=61)),
                ('district', models.IntegerField(max_length=12)),
                ('category', models.CharField(max_length=50)),
                ('call_date_time', models.DateTimeField()),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=3857)),
            ],
        ),
    ]
