# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-06 06:12
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimemap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='calls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_fid', models.IntegerField()),
                ('calldate', models.CharField(max_length=10)),
                ('objectid', models.IntegerField()),
                ('nature', models.CharField(max_length=16)),
                ('callid', models.IntegerField()),
                ('councildistrict', models.CharField(max_length=1)),
                ('join_count', models.IntegerField()),
                ('callcategory', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=61)),
                ('calldatetime', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=3857)),
            ],
        ),
        migrations.DeleteModel(
            name='Call',
        ),
    ]
