# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimemap', '0002_auto_20160505_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calls',
            name='calldate',
        ),
        migrations.RemoveField(
            model_name='calls',
            name='councildistrict',
        ),
        migrations.RemoveField(
            model_name='calls',
            name='id',
        ),
        migrations.RemoveField(
            model_name='calls',
            name='join_count',
        ),
        migrations.RemoveField(
            model_name='calls',
            name='objectid',
        ),
        migrations.RemoveField(
            model_name='calls',
            name='target_fid',
        ),
        migrations.RemoveField(
            model_name='calls',
            name='calldatetime',
        ),
        migrations.AlterField(
            model_name='calls',
            name='callid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
