# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimemap', '0004_auto_20160507_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='calls',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calls',
            name='lon',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
